version: "3"
services:
  postfix:
    restart: always
    build:
      context: postfix/.
      args:
        MAIL_DOMAIN: ${MAIL_DOMAIN}
    volumes:
      - mailadm-db:/var/lib/mailadm/
      - ./certs/:/certs/
    ports:
      - "587:587"
    networks:
      - mail
  dovecot:
    restart: always
    volumes:
      - mailadm-db:/var/lib/mailadm/
      - ./certs/:/certs/
    build:
      context: dovecot/.
      args:
        VMAIL_UID: ${VMAIL_UID}
        VMAIL_GID: ${VMAIL_GID}
    ports:
      - "143:143"
    networks:
      - mail
  mailadm:
    restart: always
    volumes:
      - mailadm-db:/var/lib/mailadm/
    build:
      context: mailadm/.
      dockerfile: Dockerfile
      args:
        VMAIL_UID: ${VMAIL_UID}
        VMAIL_GID: ${VMAIL_GID}
        MAIL_DOMAIN: ${MAIL_DOMAIN}
        WEB_ENDPOINT: https://${MAIL_DOMAIN}/new_email
    networks:
      - web
  nginx:
    restart: always
    depends_on:
      - mailadm
    volumes:
      - ./certs/:/certs/
    build:
      context: nginx/.
      dockerfile: Dockerfile
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"

volumes:
  mailadm-db:

networks:
  # Network to isolate mailadm and nginx from email services
  web:
  mail:
